### ISSUE TITLE
Improve README.md file

### ISSUE THREAD

**Issue by didaquis** [ianl15963247/pits-comp#1]
Hi. Could you update the readme.md file to include more information? 
I would like to know how install, how executed and what requirements I need to run it.

Thanks

**Comment by ianl15963247** [comment]
Hi @didaquis 
Apologies.
This repo was used mainly for my own testing purpose, should actually be private repo.
And the project is halt for a while since 14 Feb.
I recommend looking into github.com/cairinmichie  
He has done and tested on similar things
